# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Geonsu Yoon
tagline:          
description :     'Now working in Advanced Driving Assistance System S/W'
description2:     'Interested in Visual Odometry, Image Understanding.'
description3:      'Majored in Electronic Engineering.'
url:              http://gs-yoon.github.io
baseurl:          


author:
  name:           Geonsu Yoon
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/
