# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Geonsu Yoon
tagline:          'cv'
description:      '· Majored in electrical engineering.'
description2:     '· Interested in visual odometry, image understandidng.'
description3:     '· Now working in advanced driving assitance system platform sw'
url:              http://gs-yoon.github.io
baseurl:          


author:
  name:           Geonsu Yoon
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
