# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Geonsu Yoon
tagline:          'cv'
description:      'online cv'
url:              http://gsyoon.ocv.com
baseurl:          /


author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  
  
defaults:
  scope:
    type: "pages"
  values:
    layout: "page"
